# Site settings
title: shinonome-lab
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The best way to learn is to teach.So this blog is simply aimed at strengthening what
  I`ve learned.And if anyone of you could benefit from this,it will be great pleasure!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nichijou_lab
github_username:  shinonome-lab

# Build settings
markdown: kramdown
